AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for slack-games

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-ping
      PackageType: Image
      ImageConfig:
        Command: [ "app.ping" ]
      Architectures:
        - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /ping
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1
  UrlVerifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-url-verify
      PackageType: Image
      ImageConfig:
        Command: [ "app.url_verify" ]
      Architectures:
        - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /url-verify
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1

Outputs:
  MyApiGateway:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  PingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PingFunction.Arn
  PingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PingFunctionRole.Arn
